# Generated by Django 5.0.6 on 2024-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_model',
            name='About_video',
            field=models.URLField(blank=True, default='https://www.youtube.com/embed/placeholder', null=True, unique=True),
        ),
    ]
