# Generated by Django 5.0.6 on 2024-06-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisiapp', '0002_alter_about_model_about_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_model',
            name='About_video',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='noticemodel',
            name='main_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
