# Generated by Django 5.0.6 on 2024-06-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisiapp', '0003_alter_about_model_about_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_model',
            name='category',
        ),
        migrations.DeleteModel(
            name='Event_Categoty',
        ),
        migrations.DeleteModel(
            name='Event_Model',
        ),
    ]
